apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      # imagePullSecrets:
      #   - name: my-ecr-key
      containers:
        - name: boardgame
          image: $(ECR_REGISTRY)/$(ECR_REPOSITORY):$(IMAGE_TAG)
          # image: 117001856078.dkr.ecr.ap-southeast-1.amazonaws.com/boardgame:1.0.0.m1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30060
  type: LoadBalancer
